@extends('layouts.app')
@section('title', 'Payroll Batches')

@section('content')
    <div class="container-fluid" data-layout="container">
        <div class="content">

            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    {{ $errors->first() }}
                </div>
            @endif

            <div class="card shadow-sm border-0">
                <div class="card-header bg-light d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="mb-0">Payroll Batches</h5>
                        <small class="text-muted">Generated payroll per cutoff</small>
                    </div>

                    <a href="{{ route('payroll.create') }}" class="btn btn-primary btn-sm">
                        <i class="fas fa-plus me-1"></i> Generate Payroll
                    </a>
                </div>

                <div class="card-body">
                    <form method="GET" action="{{ route('payroll.index') }}" class="row g-2 mb-3">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control"
                                placeholder="Search payroll number / type / status" value="{{ request('search') }}">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-secondary">Search</button>
                        </div>
                    </form>

                    <div class="table-responsive">
                        <table class="table table-hover align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th>Payroll No.</th>
                                    <th>Cutoff</th>
                                    <th>Coverage</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Generated At</th>
                                    <th width="160">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($payrolls as $payroll)
                                    <tr>
                                        <td>
                                            <strong>{{ $payroll->payroll_number }}</strong>
                                        </td>
                                        <td>
                                            {{ $payroll->cutoff_type === 'first' ? '1st Cutoff (11–25)' : '2nd Cutoff (26–10)' }}<br>
                                            <small class="text-muted">
                                                {{ \Carbon\Carbon::create($payroll->cutoff_year, $payroll->cutoff_month, 1)->format('F Y') }}
                                            </small>
                                        </td>
                                        <td>
                                            {{ optional($payroll->period_start)->format('M d, Y') }} -
                                            {{ optional($payroll->period_end)->format('M d, Y') }}
                                        </td>
                                        <td>
                                            <span
                                                class="badge {{ $payroll->status === 'draft' ? 'bg-warning text-dark' : 'bg-success' }}">
                                                {{ ucfirst($payroll->status) }}
                                            </span>
                                        </td>
                                        <td>{{ $payroll->generator->name ?? 'N/A' }}</td>
                                        <td>{{ optional($payroll->generated_at)->format('M d, Y h:i A') }}</td>
                                        <td>
                                            <div class="d-flex gap-1">
                                                <a href="{{ route('payroll.show', $payroll) }}"
                                                    class="btn btn-primary btn-sm">
                                                    View
                                                </a>

                                                @if ($payroll->status !== 'finalized')
                                                    <form method="POST" action="{{ route('payroll.destroy', $payroll) }}"
                                                        onsubmit="return confirm('Delete this payroll batch?')">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                @endif
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7" class="text-center text-muted py-4">
                                            No payroll records found.
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    {{ $payrolls->links('pagination.custom') }}
                </div>
            </div>

        </div>
    </div>
@endsection
