@extends('layouts.app')
@section('title', 'Payroll Details')

@section('content')
    <div class="container-fluid" data-layout="container">
        <div class="content">

            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">{{ $errors->first() }}</div>
            @endif

            <div class="card shadow-sm border-0 mb-3">
                <div class="card-header bg-light d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="mb-0">Payroll Details</h5>
                        <small class="text-muted">{{ $payroll->cutoff_label }}</small>
                    </div>

                    <div class="d-flex gap-2">
                        <a href="{{ route('payroll.export.excel', $payroll) }}" class="btn btn-success btn-sm">
                            Excel
                        </a>
                        <a href="{{ route('payroll.export.pdf', $payroll) }}" class="btn btn-danger btn-sm">
                            PDF
                        </a>
                        <a href="{{ route('payroll.index') }}" class="btn btn-light btn-sm">
                            Back
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row g-3 align-items-end">
                        <div class="col-md-2">
                            <small class="text-muted d-block">Payroll Number</small>
                            <strong>{{ $payroll->payroll_number }}</strong>
                        </div>
                        <div class="col-md-2">
                            <small class="text-muted d-block">Status</small>
                            <span class="badge {{ $payroll->status === 'draft' ? 'bg-warning text-dark' : 'bg-success' }}">
                                {{ ucfirst($payroll->status) }}
                            </span>
                        </div>
                        <div class="col-md-2">
                            <small class="text-muted d-block">Generated By</small>
                            <strong>{{ $payroll->generator->name ?? 'N/A' }}</strong>
                        </div>
                        <div class="col-md-3">
                            <small class="text-muted d-block">Generated At</small>
                            <strong>{{ optional($payroll->generated_at)->format('M d, Y h:i A') }}</strong>
                        </div>
                        <div class="col-md-3">
                            <small class="text-muted d-block">Finalized</small>
                            <strong>
                                @if ($payroll->finalized_at)
                                    {{ optional($payroll->finalized_at)->format('M d, Y h:i A') }}
                                    by {{ $payroll->finalizer->name ?? 'N/A' }}
                                @else
                                    Not yet finalized
                                @endif
                            </strong>
                        </div>
                    </div>

                    @if ($payroll->status !== 'finalized')
                        <div class="mt-3">
                            <form method="POST" action="{{ route('payroll.finalize', $payroll) }}"
                                onsubmit="return confirm('Finalize this payroll? This should be treated as locked for processing.')">
                                @csrf
                                <button type="submit" class="btn btn-primary btn-sm">
                                    Finalize Payroll
                                </button>
                            </form>
                        </div>
                    @endif
                </div>
            </div>

            <div class="row g-3 mb-3">
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Gross Pay</small>
                            <h5 class="mb-0">{{ number_format($totals['gross_pay'], 2) }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Govt Deductions</small>
                            <h5 class="mb-0">{{ number_format($totals['total_employee_government_deductions'], 2) }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Late + UT + Absence</small>
                            <h5 class="mb-0">
                                {{ number_format($totals['late_deduction'] + $totals['undertime_deduction'] + $totals['absence_deduction'], 2) }}
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Net Pay</small>
                            <h5 class="mb-0">{{ number_format($totals['net_pay'], 2) }}</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card shadow-sm border-0">
                <div class="card-header bg-light">
                    <h5 class="mb-0">Payroll Employee Breakdown</h5>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th>Employee</th>
                                    <th>Payable</th>
                                    <th>Late / UT / OT</th>
                                    <th>Gross</th>
                                    <th>Government</th>
                                    <th>Other Deductions</th>
                                    <th>Net</th>
                                    <th width="90">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($payroll->items as $item)
                                    <tr>
                                        <td>
                                            <strong>{{ $item->employee_name }}</strong><br>
                                            <small class="text-muted">
                                                {{ $item->employee_no ?: 'No Employee No' }}
                                                @if ($item->biometric_employee_id)
                                                    | Bio ID: {{ $item->biometric_employee_id }}
                                                @endif
                                            </small>
                                        </td>
                                        <td>
                                            {{ number_format($item->total_payable_days, 2) }} day<br>
                                            <small class="text-muted">{{ number_format($item->total_payable_hours, 2) }}
                                                hr</small>
                                        </td>
                                        <td>
                                            Late: {{ $item->total_late_minutes }} min<br>
                                            UT: {{ $item->total_undertime_minutes }} min<br>
                                            OT: {{ $item->total_overtime_minutes }} min
                                        </td>
                                        <td>{{ number_format($item->gross_pay, 2) }}</td>
                                        <td>
                                            SSS: {{ number_format($item->sss_employee, 2) }}<br>
                                            PHIC: {{ number_format($item->philhealth_employee, 2) }}<br>
                                            HDMF: {{ number_format($item->pagibig_employee, 2) }}
                                            <br>
                                            <small class="text-muted">
                                                {{ data_get($item->meta, 'government_schedule') }}
                                            </small>
                                        </td>
                                        <td>
                                            Late/UT/Absence:
                                            {{ number_format($item->late_deduction + $item->undertime_deduction + $item->absence_deduction, 2) }}<br>
                                            Salary Deductions:
                                            {{ number_format($item->other_deductions, 2) }}
                                        </td>
                                        <td><strong>{{ number_format($item->net_pay, 2) }}</strong></td>
                                        <td>
                                            <a href="{{ route('payroll.items.show', [$payroll, $item]) }}"
                                                class="btn btn-primary btn-sm">
                                                View
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" class="text-center text-muted py-4">
                                            No payroll items found.
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                            @if ($payroll->items->isNotEmpty())
                                <tfoot class="table-light">
                                    <tr>
                                        <th colspan="3" class="text-end">TOTAL</th>
                                        <th>{{ number_format($totals['gross_pay'], 2) }}</th>
                                        <th>{{ number_format($totals['total_employee_government_deductions'], 2) }}</th>
                                        <th>{{ number_format($totals['late_deduction'] + $totals['undertime_deduction'] + $totals['absence_deduction'], 2) }}
                                        </th>
                                        <th>{{ number_format($totals['net_pay'], 2) }}</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            @endif
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection
