import {
    ArrowLeftRight,
    Banknote,
    Bus,
    BusFront,
    CalendarClock,
    CalendarDays,
    CalendarHeart,
    ChartColumn,
    Cctv,
    Circle,
    ClipboardCheck,
    ClipboardList,
    FileClock,
    FileSpreadsheet,
    FingerprintPattern,
    Gauge,
    HandHeart,
    IdCard,
    Keyboard,
    Laptop,
    LayoutDashboard,
    List,
    Package,
    PackageOpen,
    Shield,
    ShieldCheck,
    SquarePen,
    Tags,
    Ticket,
    UserCog,
    Users,
    Wallet,
    Warehouse,
    Wrench,
    type LucideIcon,
} from 'lucide-react';

/** Icon names sent by App\Support\Navigation\MainNavigation. */
const icons: Record<string, LucideIcon> = {
    'arrow-left-right': ArrowLeftRight,
    banknote: Banknote,
    bus: Bus,
    'bus-front': BusFront,
    'calendar-clock': CalendarClock,
    'calendar-days': CalendarDays,
    'calendar-heart': CalendarHeart,
    'chart-column': ChartColumn,
    cctv: Cctv,
    'clipboard-check': ClipboardCheck,
    'clipboard-list': ClipboardList,
    'file-spreadsheet': FileSpreadsheet,
    fingerprint: FingerprintPattern,
    gauge: Gauge,
    'hand-heart': HandHeart,
    history: FileClock,
    'id-card': IdCard,
    keyboard: Keyboard,
    laptop: Laptop,
    'layout-dashboard': LayoutDashboard,
    list: List,
    package: Package,
    'package-open': PackageOpen,
    shield: Shield,
    'shield-check': ShieldCheck,
    'square-pen': SquarePen,
    tags: Tags,
    ticket: Ticket,
    'user-cog': UserCog,
    users: Users,
    wallet: Wallet,
    warehouse: Warehouse,
    wrench: Wrench,
};

export function NavIcon({ name, className }: { name: string | null; className?: string }) {
    const Icon = (name && icons[name]) || Circle;

    return <Icon className={className} />;
}
