
<?php $__env->startSection('title', 'Payroll Batches'); ?>

<?php $__env->startSection('content'); ?>
    <div class="container-fluid" data-layout="container">
        <div class="content">

            <?php if(session('success')): ?>
                <div class="alert alert-success"><?php echo e(session('success')); ?></div>
            <?php endif; ?>

            <?php if($errors->any()): ?>
                <div class="alert alert-danger">
                    <?php echo e($errors->first()); ?>

                </div>
            <?php endif; ?>

            <div class="card shadow-sm border-0">
                <div class="card-header bg-light d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="mb-0">Payroll Batches</h5>
                        <small class="text-muted">Generated payroll per cutoff</small>
                    </div>

                    <a href="<?php echo e(route('payroll.create')); ?>" class="btn btn-primary btn-sm">
                        <i class="fas fa-plus me-1"></i> Generate Payroll
                    </a>
                </div>

                <div class="card-body">
                    <form method="GET" action="<?php echo e(route('payroll.index')); ?>" class="row g-2 mb-3">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control"
                                placeholder="Search payroll number / type / status" value="<?php echo e(request('search')); ?>">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-secondary">Search</button>
                        </div>
                    </form>

                    <div class="table-responsive">
                        <table class="table table-hover align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th>Payroll No.</th>
                                    <th>Cutoff</th>
                                    <th>Coverage</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Generated At</th>
                                    <th width="160">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $__empty_1 = true; $__currentLoopData = $payrolls; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $payroll): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td>
                                            <strong><?php echo e($payroll->payroll_number); ?></strong>
                                        </td>
                                        <td>
                                            <?php echo e($payroll->cutoff_type === 'first' ? '1st Cutoff (11–25)' : '2nd Cutoff (26–10)'); ?><br>
                                            <small class="text-muted">
                                                <?php echo e(\Carbon\Carbon::create($payroll->cutoff_year, $payroll->cutoff_month, 1)->format('F Y')); ?>

                                            </small>
                                        </td>
                                        <td>
                                            <?php echo e(optional($payroll->period_start)->format('M d, Y')); ?> -
                                            <?php echo e(optional($payroll->period_end)->format('M d, Y')); ?>

                                        </td>
                                        <td>
                                            <span
                                                class="badge <?php echo e($payroll->status === 'draft' ? 'bg-warning text-dark' : 'bg-success'); ?>">
                                                <?php echo e(ucfirst($payroll->status)); ?>

                                            </span>
                                        </td>
                                        <td><?php echo e($payroll->generator->name ?? 'N/A'); ?></td>
                                        <td><?php echo e(optional($payroll->generated_at)->format('M d, Y h:i A')); ?></td>
                                        <td>
                                            <div class="d-flex gap-1">
                                                <a href="<?php echo e(route('payroll.show', $payroll)); ?>"
                                                    class="btn btn-primary btn-sm">
                                                    View
                                                </a>

                                                <?php if($payroll->status !== 'finalized'): ?>
                                                    <form method="POST" action="<?php echo e(route('payroll.destroy', $payroll)); ?>"
                                                        onsubmit="return confirm('Delete this payroll batch?')">
                                                        <?php echo csrf_field(); ?>
                                                        <?php echo method_field('DELETE'); ?>
                                                        <button class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                <?php endif; ?>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="7" class="text-center text-muted py-4">
                                            No payroll records found.
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>

                    <?php echo e($payrolls->links('pagination.custom')); ?>

                </div>
            </div>

        </div>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\esgroup.version.2\resources\views/payroll/payrolls/index.blade.php ENDPATH**/ ?>