
<?php $__env->startSection('title', 'Payroll Details'); ?>

<?php $__env->startSection('content'); ?>
    <div class="container-fluid" data-layout="container">
        <div class="content">

            <?php if(session('success')): ?>
                <div class="alert alert-success"><?php echo e(session('success')); ?></div>
            <?php endif; ?>

            <?php if($errors->any()): ?>
                <div class="alert alert-danger"><?php echo e($errors->first()); ?></div>
            <?php endif; ?>

            <div class="card shadow-sm border-0 mb-3">
                <div class="card-header bg-light d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="mb-0">Payroll Details</h5>
                        <small class="text-muted"><?php echo e($payroll->cutoff_label); ?></small>
                    </div>

                    <div class="d-flex gap-2">
                        <a href="<?php echo e(route('payroll.export.excel', $payroll)); ?>" class="btn btn-success btn-sm">
                            Excel
                        </a>
                        <a href="<?php echo e(route('payroll.export.pdf', $payroll)); ?>" class="btn btn-danger btn-sm">
                            PDF
                        </a>
                        <a href="<?php echo e(route('payroll.index')); ?>" class="btn btn-light btn-sm">
                            Back
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row g-3 align-items-end">
                        <div class="col-md-2">
                            <small class="text-muted d-block">Payroll Number</small>
                            <strong><?php echo e($payroll->payroll_number); ?></strong>
                        </div>
                        <div class="col-md-2">
                            <small class="text-muted d-block">Status</small>
                            <span class="badge <?php echo e($payroll->status === 'draft' ? 'bg-warning text-dark' : 'bg-success'); ?>">
                                <?php echo e(ucfirst($payroll->status)); ?>

                            </span>
                        </div>
                        <div class="col-md-2">
                            <small class="text-muted d-block">Generated By</small>
                            <strong><?php echo e($payroll->generator->name ?? 'N/A'); ?></strong>
                        </div>
                        <div class="col-md-3">
                            <small class="text-muted d-block">Generated At</small>
                            <strong><?php echo e(optional($payroll->generated_at)->format('M d, Y h:i A')); ?></strong>
                        </div>
                        <div class="col-md-3">
                            <small class="text-muted d-block">Finalized</small>
                            <strong>
                                <?php if($payroll->finalized_at): ?>
                                    <?php echo e(optional($payroll->finalized_at)->format('M d, Y h:i A')); ?>

                                    by <?php echo e($payroll->finalizer->name ?? 'N/A'); ?>

                                <?php else: ?>
                                    Not yet finalized
                                <?php endif; ?>
                            </strong>
                        </div>
                    </div>

                    <?php if($payroll->status !== 'finalized'): ?>
                        <div class="mt-3">
                            <form method="POST" action="<?php echo e(route('payroll.finalize', $payroll)); ?>"
                                onsubmit="return confirm('Finalize this payroll? This should be treated as locked for processing.')">
                                <?php echo csrf_field(); ?>
                                <button type="submit" class="btn btn-primary btn-sm">
                                    Finalize Payroll
                                </button>
                            </form>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row g-3 mb-3">
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Gross Pay</small>
                            <h5 class="mb-0"><?php echo e(number_format($totals['gross_pay'], 2)); ?></h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Govt Deductions</small>
                            <h5 class="mb-0"><?php echo e(number_format($totals['total_employee_government_deductions'], 2)); ?></h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Late + UT + Absence</small>
                            <h5 class="mb-0">
                                <?php echo e(number_format($totals['late_deduction'] + $totals['undertime_deduction'] + $totals['absence_deduction'], 2)); ?>

                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card shadow-sm border-0">
                        <div class="card-body">
                            <small class="text-muted d-block">Net Pay</small>
                            <h5 class="mb-0"><?php echo e(number_format($totals['net_pay'], 2)); ?></h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card shadow-sm border-0">
                <div class="card-header bg-light">
                    <h5 class="mb-0">Payroll Employee Breakdown</h5>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th>Employee</th>
                                    <th>Payable</th>
                                    <th>Late / UT / OT</th>
                                    <th>Gross</th>
                                    <th>Government</th>
                                    <th>Other Deductions</th>
                                    <th>Net</th>
                                    <th width="90">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $__empty_1 = true; $__currentLoopData = $payroll->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td>
                                            <strong><?php echo e($item->employee_name); ?></strong><br>
                                            <small class="text-muted">
                                                <?php echo e($item->employee_no ?: 'No Employee No'); ?>

                                                <?php if($item->biometric_employee_id): ?>
                                                    | Bio ID: <?php echo e($item->biometric_employee_id); ?>

                                                <?php endif; ?>
                                            </small>
                                        </td>
                                        <td>
                                            <?php echo e(number_format($item->total_payable_days, 2)); ?> day<br>
                                            <small class="text-muted"><?php echo e(number_format($item->total_payable_hours, 2)); ?>

                                                hr</small>
                                        </td>
                                        <td>
                                            Late: <?php echo e($item->total_late_minutes); ?> min<br>
                                            UT: <?php echo e($item->total_undertime_minutes); ?> min<br>
                                            OT: <?php echo e($item->total_overtime_minutes); ?> min
                                        </td>
                                        <td><?php echo e(number_format($item->gross_pay, 2)); ?></td>
                                        <td>
                                            SSS: <?php echo e(number_format($item->sss_employee, 2)); ?><br>
                                            PHIC: <?php echo e(number_format($item->philhealth_employee, 2)); ?><br>
                                            HDMF: <?php echo e(number_format($item->pagibig_employee, 2)); ?>

                                            <br>
                                            <small class="text-muted">
                                                <?php echo e(data_get($item->meta, 'government_schedule')); ?>

                                            </small>
                                        </td>
                                        <td>
                                            Late/UT/Absence:
                                            <?php echo e(number_format($item->late_deduction + $item->undertime_deduction + $item->absence_deduction, 2)); ?><br>
                                            Salary Deductions:
                                            <?php echo e(number_format($item->other_deductions, 2)); ?>

                                        </td>
                                        <td><strong><?php echo e(number_format($item->net_pay, 2)); ?></strong></td>
                                        <td>
                                            <a href="<?php echo e(route('payroll.items.show', [$payroll, $item])); ?>"
                                                class="btn btn-primary btn-sm">
                                                View
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="8" class="text-center text-muted py-4">
                                            No payroll items found.
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                            <?php if($payroll->items->isNotEmpty()): ?>
                                <tfoot class="table-light">
                                    <tr>
                                        <th colspan="3" class="text-end">TOTAL</th>
                                        <th><?php echo e(number_format($totals['gross_pay'], 2)); ?></th>
                                        <th><?php echo e(number_format($totals['total_employee_government_deductions'], 2)); ?></th>
                                        <th><?php echo e(number_format($totals['late_deduction'] + $totals['undertime_deduction'] + $totals['absence_deduction'], 2)); ?>

                                        </th>
                                        <th><?php echo e(number_format($totals['net_pay'], 2)); ?></th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            <?php endif; ?>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\esgroup.version.2\resources\views/payroll/payrolls/show.blade.php ENDPATH**/ ?>