import { router } from '@inertiajs/react';
import { ArrowRight, Eye, Lock, Plus, Trash2 } from 'lucide-react';
import { ConfirmAction, IconButton } from '@/components/confirm-action';
import { DataTable, type DataTableColumn } from '@/components/data-table/data-table';
import { ModalLink } from '@/components/modal/modal-link';
import { openModal } from '@/components/modal/modal-store';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { definePage } from '@/lib/define-page';
import { tones } from '@/lib/dashboard-tones';
import type { Paginated } from '@/types';

interface PayrollRow {
    id: number;
    payroll_number: string;
    cutoff_label: string;
    period_start: string | null;
    period_end: string | null;
    contribution_label: string;
    items_count: number;
    group_label: string;
    is_finalized: boolean;
    generator_name: string;
    generated_at: string | null;
    urls: { show: string; destroy: string };
}

interface Props {
    payrolls: Paginated<PayrollRow>;
    filters: { search: string; status: string; cutoff_type: string; garage_group: string };
    cutoffTypes: Record<string, string>;
    payrollGroups: Record<string, string>;
    can: { create: boolean; delete: boolean };
    urls: { index: string; create: string };
}

const options = (record: Record<string, string>) => Object.entries(record).map(([value, label]) => ({ value, label }));

export default definePage<Props>({
    title: () => 'Payroll',
    description: () => 'Generated payroll periods and their processing status. Open a batch to review, export or finalize it.',
    actions: ({ can, urls }) =>
        can.create && (
            <Button asChild>
                <ModalLink href={urls.create} mode="form">
                    <Plus />
                    Generate Payroll
                </ModalLink>
            </Button>
        ),
    Content: PayrollIndex,
});

function PayrollIndex({ payrolls, filters, cutoffTypes, payrollGroups, can, urls }: Props) {
    const columns: DataTableColumn<PayrollRow>[] = [
        {
            key: 'batch',
            header: 'Payroll batch',
            cell: (row) => (
                <>
                    <ModalLink href={row.urls.show} className="font-medium hover:underline" onClick={(event) => event.stopPropagation()}>
                        {row.payroll_number}
                    </ModalLink>
                    <div className="max-w-56 text-xs text-muted-foreground">{row.cutoff_label}</div>
                </>
            ),
            filter: { type: 'select', param: 'cutoff_type', options: options(cutoffTypes), placeholder: 'All cutoffs' },
        },
        {
            key: 'coverage',
            header: 'Coverage',
            className: 'whitespace-nowrap text-sm',
            cell: (row) => (
                <span className="inline-flex items-center gap-1.5">
                    {row.period_start ?? 'N/A'}
                    <ArrowRight className="size-3 text-muted-foreground" />
                    {row.period_end ?? 'N/A'}
                </span>
            ),
        },
        { key: 'contribution', header: 'Contribution', hideBelow: '2xl', className: 'text-sm', cell: (row) => row.contribution_label },
        { key: 'employees', header: 'Employees', align: 'center', className: 'tabular-nums', cell: (row) => row.items_count.toLocaleString() },
        {
            key: 'group',
            header: 'Payroll group',
            hideBelow: 'lg',
            className: 'text-sm',
            cell: (row) => row.group_label,
            filter: { type: 'select', param: 'garage_group', options: options(payrollGroups), placeholder: 'All groups' },
        },
        {
            key: 'status',
            header: 'Status',
            cell: (row) =>
                row.is_finalized ? (
                    <Badge variant="outline" className={tones.GREEN}>
                        Finalized
                    </Badge>
                ) : (
                    <Badge variant="secondary">Draft</Badge>
                ),
            filter: {
                type: 'select',
                param: 'status',
                options: [
                    { value: 'draft', label: 'Draft' },
                    { value: 'finalized', label: 'Finalized' },
                ],
                placeholder: 'All statuses',
            },
        },
        {
            key: 'generated',
            header: 'Generated by',
            hideBelow: '2xl',
            className: 'text-sm',
            cell: (row) => (
                <>
                    <div>{row.generator_name}</div>
                    <div className="text-xs text-muted-foreground">{row.generated_at ?? 'N/A'}</div>
                </>
            ),
        },
    ];

    return (
        <DataTable
            title="Payroll records"
            noun="batch"
            paginator={payrolls}
            url={urls.index}
            filters={filters}
            columns={columns}
            rowKey={(row) => row.id}
            searchPlaceholder="Search payroll number, cutoff, status or remarks..."
            emptyText="No payroll batches match the current search and filters."
            onRowClick={(row) => openModal(row.urls.show)}
            rowActions={(row) => (
                <span className="flex items-center gap-1" onClick={(event) => event.stopPropagation()}>
                    <Button variant="ghost" size="icon" className="size-8" asChild>
                        <ModalLink href={row.urls.show} aria-label={`View ${row.payroll_number}`}>
                            <Eye />
                        </ModalLink>
                    </Button>
                    {row.is_finalized ? (
                        <IconButton label="Finalized payroll is locked" disabled>
                            <Lock />
                        </IconButton>
                    ) : (
                        can.delete && (
                            <ConfirmAction
                                title="Delete draft payroll?"
                                description="Delete this draft payroll? This action cannot be undone."
                                confirmLabel="Delete"
                                destructive
                                onConfirm={() => router.delete(row.urls.destroy, { preserveScroll: true, preserveState: true })}
                                trigger={
                                    <IconButton label="Delete draft payroll">
                                        <Trash2 className="text-destructive" />
                                    </IconButton>
                                }
                            />
                        )
                    )}
                </span>
            )}
        />
    );
}
